version: "3"

services:
  fpm:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the backend)
      dockerfile: ./docker/Dockerfile-php # Specify the name of the Dockerfile
    restart: unless-stopped
    environment: # You can use this section to set environment variables. But you can also use the .env file.
      - DATABASE_URL=mysql://root:root@db:3306/backend_db # Connection string for the database.
    volumes:
      - ./backend/:/var/www/backend/ # Location of the backend for php-fpm. Note this should be the same for NGINX.
    depends_on:
      - composer_installation

  composer_installation:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the backend)
      dockerfile: ./docker/Dockerfile-composer # Specify the name of the Dockerfile
    volumes:
      - ./backend/:/app
    command: composer install --ignore-platform-reqs

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nginx
    restart: unless-stopped
    volumes:
      - ./backend/:/var/www/backend/
    ports:
      - 80:80 # Ports that are exposed, you can connect to port 8001 to port 80 of the container.
    depends_on:
      - fpm
      - db

  db:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the backend)
      dockerfile: ./docker/Dockerfile-mysql # Specify the name of the Dockerfile
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root # Setting the MYSQL credentials to root:root.
    volumes:
      - symfony_db:/var/lib/mysql:cached # Persist the database in a Docker volume.
    ports:
      - 3311:3306

  phpmyadmin:
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the backend)
      dockerfile: ./docker/Dockerfile-phpmyadmin # Specify the name of the Dockerfile
    container_name: ktebna_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://db.ktebna.tn/
    depends_on:
      - db

  angular: # The name of the service
    build: # Info to build the Docker image
      context: . # Specify where the Dockerfile is located (e.g. in the root directory of the backend)
      dockerfile: ./docker/Dockerfile-angular # Specify the name of the Dockerfile
    container_name: ktebna_angular
    restart: unless-stopped
    volumes: # Volume binding
      - ./frontend/:/usr/src/app
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --disableHostCheck"
    depends_on:
      - nginx

volumes:
  symfony_db: